### ISSUE TITLE
"More about open source" missing nouns and adjectives!

### ISSUE THREAD

**Issue by paulproteus** [csudh-1/csudh-1.github.io#7]
The "more about open source" section appears to be missing some nouns and adjectives.  What an adjective noun that is!

Can you find us some adjectives and nouns?  Any adjectives and nouns will do.

Make sure to find all of them!

**Comment by acardoso93** [comment]
I'll handle this issue

**Comment by paulproteus** [comment]
Great @acardoso93 ! Let me know if you need anything.

**Comment by paulproteus** [comment]
Closed in https://github.com/csudh-1/csudh-1.github.io/pull/9 !
